<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinationSeeder extends Seeder
{
    public function run()
    {
        DB::table('destinations')->insert([
            [
                'name' => 'Komodo National Park',
                'description' => 'A UNESCO World Heritage Site home to the world’s largest lizards and rich marine life.',
                'location' => 'Komodo Island',
                'category' => 'Nature',
                'image' => 'komodo_national_park.jpg',
                'is_popular' => true,
                'price' => 10000,
                'rating' => 4.6,
                'rating_count' => 7000,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Pink Beach',
                'description' => 'A unique beach with soft pink sand and crystal-clear waters.',
                'location' => 'Komodo Island',
                'category' => 'Beach',
                'image' => 'pink_beach.jpg',
                'is_popular' => true,
                'price' => 15000,
                'rating' => 4.8,
                'rating_count' => 3252,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Kelimutu National Park',
                'description' => 'Famous for its three colored volcanic lakes that change color periodically.',
                'location' => 'Ende, Flores',
                'category' => 'Mountain',
                'image' => 'kelimutu_lake.jpg',
                'is_popular' => true,
                'price' => 20000,
                'rating' => 4.9,
                'rating_count' => 4210,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Wae Rebo Village',
                'description' => 'A traditional Manggarai village with iconic cone-shaped houses, located above the clouds.',
                'location' => 'Manggarai, Flores',
                'category' => 'Cultural',
                'image' => 'wae_rebo.jpg',
                'is_popular' => true,
                'price' => 25000,
                'rating' => 4.7,
                'rating_count' => 1893,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Labuan Bajo',
                'description' => 'A lively harbor town known as the gateway to Komodo National Park.',
                'location' => 'Flores',
                'category' => 'City',
                'image' => 'labuan_bajo.jpg',
                'is_popular' => true,
                'price' => 0,
                'rating' => 4.5,
                'rating_count' => 5320,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Alor Island',
                'description' => 'A hidden gem with pristine beaches, traditional villages, and world-class diving.',
                'location' => 'Alor',
                'category' => 'Island',
                'image' => 'alor_island.jpg',
                'is_popular' => false,
                'price' => 10000,
                'rating' => 4.4,
                'rating_count' => 980,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Rote Island',
                'description' => 'Indonesia’s southernmost island, popular for surfing and traditional culture.',
                'location' => 'Rote Ndao',
                'category' => 'Island',
                'image' => 'rote_island.jpg',
                'is_popular' => false,
                'price' => 5000,
                'rating' => 4.3,
                'rating_count' => 1200,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Sumba Island',
                'description' => 'Known for unique culture, megalithic tombs, and beautiful beaches.',
                'location' => 'Sumba',
                'category' => 'Island',
                'image' => 'sumba_island.jpg',
                'is_popular' => true,
                'price' => 15000,
                'rating' => 4.7,
                'rating_count' => 2750,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Kupang City',
                'description' => 'The capital of East Nusa Tenggara, famous for beaches, caves, and local cuisine.',
                'location' => 'Kupang, Timor',
                'category' => 'City',
                'image' => 'kupang_city.jpg',
                'is_popular' => false,
                'price' => 0,
                'rating' => 4.2,
                'rating_count' => 1890,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
            [
                'name' => 'Savu Island',
                'description' => 'A remote island with traditional weaving culture and untouched beaches.',
                'location' => 'Savu',
                'category' => 'Island',
                'image' => 'savu_island.jpg',
                'is_popular' => false,
                'price' => 5000,
                'rating' => 4.1,
                'rating_count' => 640,
                'latitude' => null,
                'longitude' => null,
                'maps_url' => null,
            ],
        ]);
    }
}
