<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Peta lokasi ke destination_id untuk data yang lebih terstruktur
        $destinationMapping = [
            'Labuan Bajo' => 1,
            'Komodo Island' => 2,
            'Kupang' => 3,
            'Sumba Barat Daya' => 4,
            'Kanawa Island' => 5,
            'Waingapu' => 6,
            'Rote Island' => 7,
            'Ende' => 8,
            'Maumere' => 9,
            'Bajawa' => 10,
            'Ruteng' => 11,
            'Alor Regency' => 12,
            'Sumba Barat' => 13,
        ];

        DB::table('hotels')->insert([
            [
                'name' => 'Plataran Komodo Resort & Spa',
                'address' => 'Labuan Bajo',
                'description' => 'Luxury beachfront resort with spa, diving and sunset views.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Pool, Spa, Restaurant, Airport Shuttle',
                'location' => 'Labuan Bajo',
                'single_room_price' => 1500000,
                'double_room_price' => 2000000,
                'family_room_price' => 3000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Puri Sari Beach Hotel',
                'address' => 'Labuan Bajo',
                'description' => 'Peaceful beach hotel with tropical gardens and great hospitality.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Restaurant, Private Beach, Garden',
                'location' => 'Labuan Bajo',
                'single_room_price' => 850000,
                'double_room_price' => 1200000,
                'family_room_price' => 1700000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Komodo Resort & Diving Club',
                'address' => 'Komodo Island',
                'description' => 'Remote island resort ideal for divers and nature lovers.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Komodo Island'],
                'facilities' => 'Diving Center, Restaurant, Beachfront',
                'location' => 'Komodo Island',
                'single_room_price' => 1400000,
                'double_room_price' => 1800000,
                'family_room_price' => 2500000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Seaesta Komodo Hotel & Hostel',
                'address' => 'Labuan Bajo',
                'description' => 'Trendy hotel/hostel hybrid with rooftop bar and sea view.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Pool, Bar, Co-working Space',
                'location' => 'Labuan Bajo',
                'single_room_price' => 350000,
                'double_room_price' => 550000,
                'family_room_price' => 900000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'AYANA Komodo Waecicu Beach',
                'address' => 'Labuan Bajo',
                'description' => '5-star resort with private jetty and luxury rooms.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Infinity Pool, Spa, Gym, Restaurant',
                'location' => 'Labuan Bajo',
                'single_room_price' => 2000000,
                'double_room_price' => 3000000,
                'family_room_price' => 4500000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Meruorah Komodo Labuan Bajo',
                'address' => 'Labuan Bajo',
                'description' => 'Modern hotel with Komodo views, ideal for leisure and business.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Pool, Meeting Rooms, Restaurant',
                'location' => 'Labuan Bajo',
                'single_room_price' => 1600000,
                'double_room_price' => 2200000,
                'family_room_price' => 3500000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kristal Hotel Kupang',
                'address' => 'Kupang',
                'description' => 'Classic hotel in Kupang with sea views and event facilities.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Kupang'],
                'facilities' => 'WiFi, Pool, Restaurant, Meeting Room',
                'location' => 'Kupang',
                'single_room_price' => 600000,
                'double_room_price' => 900000,
                'family_room_price' => 1400000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Amaris Hotel Kupang',
                'address' => 'Kupang',
                'description' => 'Budget-friendly hotel in the heart of Kupang city.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Kupang'],
                'facilities' => 'WiFi, Restaurant, Parking',
                'location' => 'Kupang',
                'single_room_price' => 400000,
                'double_room_price' => 600000,
                'family_room_price' => 950000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'NIHI Sumba',
                'address' => 'Sumba Barat Daya',
                'description' => 'World-renowned luxury resort with private villas and spa.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Sumba Barat Daya'],
                'facilities' => 'Spa, Private Pool, Butler Service, Yoga',
                'location' => 'Sumba Barat Daya',
                'single_room_price' => 9000000,
                'double_room_price' => 15000000,
                'family_room_price' => 20000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lelewatu Resort Sumba',
                'address' => 'Sumba Barat Daya',
                'description' => 'Cliff-top luxury retreat offering panoramic ocean views.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Sumba Barat Daya'],
                'facilities' => 'Spa, Private Pool, Restaurant',
                'location' => 'Sumba Barat Daya',
                'single_room_price' => 7000000,
                'double_room_price' => 10000000,
                'family_room_price' => 15000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sunrise Hotel',
                'address' => 'Labuan Bajo',
                'description' => 'Simple hotel near harbor with rooftop restaurant.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Restaurant, Rooftop',
                'location' => 'Labuan Bajo',
                'single_room_price' => 400000,
                'double_room_price' => 600000,
                'family_room_price' => 1000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bintang Flores Hotel',
                'address' => 'Labuan Bajo',
                'description' => 'Hotel with beach access and poolside relaxation.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Pool, Restaurant, Private Beach',
                'location' => 'Labuan Bajo',
                'single_room_price' => 1000000,
                'double_room_price' => 1300000,
                'family_room_price' => 1900000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kanawa Beach Resort',
                'address' => 'Kanawa Island',
                'description' => 'Rustic beach resort perfect for snorkeling and diving.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Kanawa Island'],
                'facilities' => 'Restaurant, Beach Hut, Snorkeling',
                'location' => 'Kanawa Island',
                'single_room_price' => 600000,
                'double_room_price' => 800000,
                'family_room_price' => 1200000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Blue Marlin Komodo',
                'address' => 'Labuan Bajo',
                'description' => 'Diver-friendly resort with direct access to Komodo diving spots.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'Diving Center, Restaurant, WiFi',
                'location' => 'Labuan Bajo',
                'single_room_price' => 1100000,
                'double_room_price' => 1400000,
                'family_room_price' => 2000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hotel On The Rock',
                'address' => 'Kupang',
                'description' => 'Seaside hotel built on a cliff, great for sunsets.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Kupang'],
                'facilities' => 'WiFi, Pool, Restaurant, Lounge',
                'location' => 'Kupang',
                'single_room_price' => 700000,
                'double_room_price' => 1000000,
                'family_room_price' => 1500000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tanto Hotel',
                'address' => 'Waingapu',
                'description' => 'Affordable hotel with basic rooms in central Waingapu.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Waingapu'],
                'facilities' => 'WiFi, Parking, Restaurant',
                'location' => 'Waingapu',
                'single_room_price' => 300000,
                'double_room_price' => 450000,
                'family_room_price' => 700000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kambaniru Beach Hotel',
                'address' => 'Waingapu',
                'description' => 'Cozy beachside hotel with friendly service.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Waingapu'],
                'facilities' => 'Beach Access, WiFi, Garden',
                'location' => 'Waingapu',
                'single_room_price' => 400000,
                'double_room_price' => 600000,
                'family_room_price' => 900000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Utopia Rote Lodge',
                'address' => 'Rote Island',
                'description' => 'Small eco-lodge near quiet beach, ideal for relaxing.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Rote Island'],
                'facilities' => 'Restaurant, Hammocks, Beachfront',
                'location' => 'Rote Island',
                'single_room_price' => 450000,
                'double_room_price' => 650000,
                'family_room_price' => 950000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lasiana Beach Hotel',
                'address' => 'Kupang',
                'description' => 'Simple accommodation near Lasiana beach and night market.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Kupang'],
                'facilities' => 'WiFi, Parking, Local Cafe',
                'location' => 'Kupang',
                'single_room_price' => 350000,
                'double_room_price' => 550000,
                'family_room_price' => 800000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dragon Dive Komodo',
                'address' => 'Labuan Bajo',
                'description' => 'Dive-centered hotel with group packages.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'Diving Pool, Restaurant, Shared Dorm',
                'location' => 'Labuan Bajo',
                'single_room_price' => 500000,
                'double_room_price' => 700000,
                'family_room_price' => 1100000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Eco Tree O\'tel',
                'address' => 'Labuan Bajo',
                'description' => 'Eco-conscious stay with treehouse vibes and rooftop cafe.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'WiFi, Rooftop Restaurant, Green Design',
                'location' => 'Labuan Bajo',
                'single_room_price' => 600000,
                'double_room_price' => 900000,
                'family_room_price' => 1400000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Scuba Junkie Komodo',
                'address' => 'Labuan Bajo',
                'description' => 'Affordable resort focusing on diving trips and courses.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Labuan Bajo'],
                'facilities' => 'Diving Center, Dorms, Bar',
                'location' => 'Labuan Bajo',
                'single_room_price' => 550000,
                'double_room_price' => 750000,
                'family_room_price' => 1000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hotel La Hasienda',
                'address' => 'Ende',
                'description' => 'Spanish-themed hotel with comfortable rooms and friendly staff.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Ende'],
                'facilities' => 'WiFi, Restaurant, Airport Pickup',
                'location' => 'Ende',
                'single_room_price' => 400000,
                'double_room_price' => 650000,
                'family_room_price' => 1000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Capa Resort Maumere',
                'address' => 'Maumere',
                'description' => 'Stylish resort with beautiful sunrise views and coral reefs.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Maumere'],
                'facilities' => 'Pool, WiFi, Restaurant, Diving',
                'location' => 'Maumere',
                'single_room_price' => 700000,
                'double_room_price' => 950000,
                'family_room_price' => 1300000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sao Wisata Resort',
                'address' => 'Bajawa',
                'description' => 'Countryside resort with mountain views and traditional setting.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Bajawa'],
                'facilities' => 'WiFi, Local Tours, Restaurant',
                'location' => 'Bajawa',
                'single_room_price' => 500000,
                'double_room_price' => 700000,
                'family_room_price' => 1000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hotel Happy Happy',
                'address' => 'Bajawa',
                'description' => 'Homely guesthouse with friendly hosts near downtown.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Bajawa'],
                'facilities' => 'WiFi, Breakfast, Parking',
                'location' => 'Bajawa',
                'single_room_price' => 300000,
                'double_room_price' => 450000,
                'family_room_price' => 700000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Flores Sare Hotel',
                'address' => 'Ruteng',
                'description' => 'Quiet city hotel with great food and garden view.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Ruteng'],
                'facilities' => 'WiFi, Restaurant, Garden',
                'location' => 'Ruteng',
                'single_room_price' => 500000,
                'double_room_price' => 750000,
                'family_room_price' => 1000000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Budi Sun Resort',
                'address' => 'Alor',
                'description' => 'Seaside resort near diving spots and quiet bay.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Alor Regency'],
                'facilities' => 'Snorkeling, WiFi, Beachfront',
                'location' => 'Alor Regency',
                'single_room_price' => 600000,
                'double_room_price' => 800000,
                'family_room_price' => 1200000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pantai Paris Resort',
                'address' => 'Sumba Barat',
                'description' => 'Resort near untouched beaches and surfing areas.',
                'image' => 'images/hotel_placeholder.jpg',
                'destination_id' => $destinationMapping['Sumba Barat'],
                'facilities' => 'Surf Access, Restaurant, Beachfront',
                'location' => 'Sumba Barat',
                'single_room_price' => 500000,
                'double_room_price' => 700000,
                'family_room_price' => 1100000,
                'room_count_single' => 10,
                'room_count_double' => 10,
                'room_count_family' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}